### ISSUE TITLE
FormControl Detection

### ISSUE THREAD

**Issue by chederick** [ngx-material-keyboard/core#32] opened 2017-12-12 12:24 UTC
I'm trying to catch the events fired by the virtual keyboard, but i'm using a formControl, in my input.
I realize that the formControl do not detect or set the value to the model, when i type on virtual keyboard.
Is there any way to make my formControl catch the events of the keyboard ?

**Comment by davidenke** [comment] 2018-02-19 22:21
Duplicate of #31

**Closed by davidenke** 2018-02-19 22:21 UTC
Labels: duplicate
