### ISSUE TITLE
The keyboard doesn't work in the demo app either!

### ISSUE THREAD

**Issue by janos-roche** [ngx-material-keyboard/core#42] opened 2018-02-21 22:06 UTC
Change 'sushi' to something else in the onscreen keyboard and click submit you'll see in the console that the form doesn't have the value you entered. See screenshot
![screen shot 2018-02-21 at 2 04 23 pm](https://user-images.githubusercontent.com/26580548/36508031-54e12462-1710-11e8-8208-6fb1cc703a0c.jpg)

**Comment by davidenke** [comment] 2018-02-21 23:36
DUplicate of #31

**Closed by davidenke** 2018-02-21 23:36 UTC
Labels: duplicate
