### ISSUE TITLE
error on key press

### ISSUE THREAD

**Issue by praveens96** [ngx-material-keyboard/core#34] opened 2017-12-16 16:04 UTC
receiving below error on page load:

[https://user-images.githubusercontent.com/8864727/33803702-fd83fec0-ddbb-11e7-98b3-0b5c0b90ca33.png](url)
Unhandled Promise rejection: AngularJS v1.x is not loaded! ; Zone: ; Task: Promise.then ; Value: Error: AngularJS v1.x is not loaded!

when ignoring this and try to type with keyboard, then, getting below error:
[https://user-images.githubusercontent.com/8864727/33803712-369ff01a-ddbc-11e7-8b3b-eeba17811177.png](url)
MdKeyboardKeyComponent._setCursorPosition in this method, this.control value is coming as null.

any help/guidance would be appreciated?

**Comment by digaus** [comment] 2017-12-18 12:26
Try this version: https://github.com/digaus/core

Clone it, run 'npm install' and then 'npm run build'. Then copy content of dist folder to 'node_modules/ngx-material-keyboard/core'

**Comment by praveens96** [comment] 2017-12-31 17:43
it worked fine @digaus . thank you very much. appreciate your timely help..
for future googles, here is the summary of steps,
npm install --save @ngx-material-keyboard/core
npm install --save @angular/material @angular/cdk
npm install --save @angular/animations
ionic cordova plugin add ionic-plugin-keyboard //for my proj purpose
npm install --save @ionic-native/keyboard //for my proj purpose
//add below css to index.html and styles to ur component
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
//optional
npm install typescript@latest --save-dev

**Comment by praveens96** [comment] 2018-01-24 18:08
@digaus is there way to get the key pressed event? your earliest help would be much appreciated.

**Comment by drullo** [comment] 2018-02-16 17:22
Can somebody on the project dev team tell us if the fix implemented by @digaus will be implemented in this project soon?  It's rather critical.  As far as I can tell, it's just a simple fix to keyboard-key.component.ts - the `this.inputValue = this.control.value;` line needs to be wrapped in an if statement to check for the existence of this.control.

Without this fix, the keyboard essentially does not work even though it appears to.  The value that it's bound to does not get updated when keys are pressed.  This change has to be implemented.

For the time being, the workaround solution suggested by @digaus (overwriting your dist code with theirs) does solve the problem - but that's a hack.

**Comment by davidenke** [comment] 2018-02-19 22:03
The whole event handling isn't finished yet, I hope I'll have time to improve it in the next weeks.

**Comment by davidenke** [comment] 2018-02-19 22:20
Duplicate of #31

**Closed by davidenke** 2018-02-19 22:20 UTC
